# Generated by Django 4.2.14 on 2024-12-06 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0002_tip_downvotes_tip_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='downvoters',
            field=models.ManyToManyField(related_name='downvoters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tip',
            name='upvoters',
            field=models.ManyToManyField(related_name='upvoters', to=settings.AUTH_USER_MODEL),
        ),
    ]
