# Generated by Django 4.2.14 on 2024-12-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0003_tip_downvoters_tip_upvoters'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_user',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
    ]
